name: Agendar busca de vagas Gupy

on:
  schedule:
    - cron: "0 */4 * * *"  # A cada 4 horas
  workflow_dispatch:

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install --default-timeout=300 --retries=3 -r requirements.txt

      - name: Configurar variáveis de ambiente
        run: |
          echo '${{ secrets.GSHEET_CREDENTIALS_JSON }}' > credenciais.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=credenciais.json" >> $GITHUB_ENV
          echo "EMAIL_RECEPTOR=${{ secrets.EMAIL_RECEPTOR }}" >> $GITHUB_ENV
          echo "EMAIL_REMETENTE=${{ secrets.EMAIL_REMETENTE }}" >> $GITHUB_ENV
          echo "SENHA_REMETENTE=${{ secrets.SENHA_REMETENTE }}" >> $GITHUB_ENV

      - name: Executar e Salvar Alterações
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git pull --rebase

          python main.py
          git add historico_vagas.csv

          if git diff --staged --quiet; then
            echo "📭 Nenhuma vaga nova encontrada. Nada para commitar."
            exit 0
          fi

          git commit -m "Atualizar histórico de vagas [automático]"
          git push