name: Agendar busca de vagas Gupy

on:
  schedule:
    - cron: "0 */4 * * *"  # Executa a cada 4 horas
  workflow_dispatch:

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install --default-timeout=300 -r requirements.txt

      - name: Configurar variáveis de ambiente e credenciais
        run: |
          echo '${{ secrets.GSHEET_CREDENTIALS_JSON }}' > credenciais.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=credenciais.json" >> $GITHUB_ENV
          echo "EMAIL_REMETENTE=${{ secrets.EMAIL_REMETENTE }}" >> $GITHUB_ENV
          echo "SENHA_APP=${{ secrets.SENHA_APP }}" >> $GITHUB_ENV
          echo "EMAIL_DESTINO=${{ secrets.EMAIL_DESTINO }}" >> $GITHUB_ENV

      - name: Executar script principal
        run: |
          python main.py

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase

      - name: Commit CSV atualizado
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add historico_vagas.csv
          git commit -m "Atualizando CSV com novas vagas" || echo "Nada para commitar"

      - name: Pull com rebase
        run: |
          git pull --rebase || echo "Sem mudanças para rebase"

          fi
