
name: Agendar busca de vagas Gupy

on:
  schedule:
    - cron: "0 */4 * * *"  # Executa a cada 4 horas
  workflow_dispatch:

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install --default-timeout=300 -r requirements.txt

      - name: Configurar variáveis de ambiente e credenciais
        run: |
          echo '${{ secrets.GSHEET_CREDENTIALS_JSON }}' > credenciais.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=credenciais.json" >> $GITHUB_ENV
          echo "EMAIL_REMETENTE=${{ secrets.EMAIL_REMETENTE }}" >> $GITHUB_ENV
          echo "SENHA_APP=${{ secrets.SENHA_APP }}" >> $GITHUB_ENV
          echo "EMAIL_DESTINO=${{ secrets.EMAIL_DESTINO }}" >> $GITHUB_ENV

      - name: Executar script principal
        run: |
          python main.py

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase

      - name: Commit e push dos arquivos atualizados
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          git add .
          git commit -m "🔄 Atualização automática de vagas - $(date '+%Y-%m-%d %H:%M:%S')" || echo "Nada para commitar"
          git push
          fi
