name: Agendar busca de vagas Gupy

on:
  schedule:
    - cron: "0 */4 * * *"  # Executa a cada 4 horas
  workflow_dispatch:

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configurar variáveis de ambiente e credenciais
        run: |
          echo '${{ secrets.GSHEET_CREDENTIALS_JSON }}' > credenciais.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=credenciais.json" >> $GITHUB_ENV
          echo "EMAIL_REMETENTE=${{ secrets.EMAIL_REMETENTE }}" >> $GITHUB_ENV
          echo "SENHA_APP=${{ secrets.SENHA_APP }}" >> $GITHUB_ENV
          echo "EMAIL_DESTINO=${{ secrets.EMAIL_DESTINO }}" >> $GITHUB_ENV

      - name: Executar script principal
        run: |
          python main.py

      - name: Fazer commit e push do histórico atualizado
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add historico_vagas.csv
          # O comando a seguir só faz o commit se houver mudanças no arquivo
          git commit -m "Atualiza histórico de vagas" || echo "Nenhuma mudança no histórico para commitar."
          git push