name: Rastrear vagas Gupy

on:
  schedule:
    - cron: "0 */4 * * *"  # A cada 4 horas
  workflow_dispatch:      # Permite rodar manualmente

jobs:
  executar_e_commitar:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    env:
      EMAIL_REMETENTE: ${{ secrets.EMAIL_REMETENTE }}
      SENHA_APP: ${{ secrets.SENHA_APP }}
      EMAIL_DESTINO: ${{ secrets.EMAIL_DESTINO }}

    steps:
      # Passo 1: Faz o checkout completo do repositório
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Passo 2: Configura o Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Passo 3: Instala as dependências
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

          # NOVO PASSO: Upload para o Google Sheets
      - name: Upload updated job history to Google Sheets
        env:
          GOOGLE_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}
          GOOGLE_SHEETS_NAME: "historico_vagas" # Nome da sua planilha no Drive
          SHEET_WORKSHEET_NAME: "Vagas" # Nome da aba na sua planilha
          run: |
            echo "Iniciando upload para o Google Sheets..."
            python upload_to_sheets.py # Executa o novo script de upload
      
      # Passo 4: Sincroniza, Executa, Commita e Faz o Push
      - name: Executar e Salvar Alterações
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git pull --ff-only
          
          python main.py
          
          git add historico_vagas.csv
          
          if git diff --staged --quiet; then
            echo "Nenhuma vaga nova encontrada. Nada para commitar."
            exit 0
          fi
          
          git commit -m "Atualizar histórico de vagas [automático]"
          git push
