name: Agendar busca de vagas Gupy

on:
  schedule:
    - cron: "0 */4 * * *"  # Executa a cada 4 horas
  workflow_dispatch:

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install --default-timeout=300 -r requirements.txt

      - name: Configurar variáveis de ambiente e credenciais
        run: |
          echo '${{ secrets.GSHEET_CREDENTIALS_JSON }}' > credenciais.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=credenciais.json" >> $GITHUB_ENV
          echo "EMAIL_RECEPTOR=${{ secrets.EMAIL_RECEPTOR }}" >> $GITHUB_ENV
          echo "EMAIL_REMETENTE=${{ secrets.EMAIL_REMETENTE }}" >> $GITHUB_ENV
          echo "SENHA_REMETENTE=${{ secrets.SENHA_REMETENTE }}" >> $GITHUB_ENV

      - name: Executar script principal
        run: |
          python main.py

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase

      - name: Commit e Push se houver alterações
        run: |
          git add historico_vagas.csv

          if git diff --staged --quiet; then
            echo "📭 Nenhuma nova vaga. Nenhuma alteração para commit."
          else
            git commit -m "Atualizar histórico de vagas [automático]"
            git push
          fi
